name: Publish Extension
run-name: Publish Extension v${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: "Version to publish (eg 1.2.3)"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: npm

      - name: Update version
        run: npm version ${{ inputs.version }} --no-git-tag-version

      - name: Install dependencies
        run: npm ci

      - name: Compile
        run: npm run compile

      - name: Pack and list files
        run: npx @vscode/vsce pack && npx @vscode/vsce ls --tree

      - name: Publish to Visual Studio Marketplace
        run: npx @vscode/vsce publish --no-git-tag-version
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # - name: Publish to Open VSX Registry
      #   run: npx ovsx publish --no-dependencies
      #   env:
      #     OVSX_PAT: ${{ secrets.OVSX_PAT }}
      #   continue-on-error: true

      - name: Create github release
        run: gh release create "v${{ inputs.version }}" --generate-notes --title "v${{ inputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
